- hosts: '{{ server | default("localhost") }}'
  vars:
    user: 'root'
    email: 'root@example.com'
    locale: 'ja_JP.UTF-8'
  vars_prompt: 
    - name: "password"
      prompt: "Enter graphite's password"
      private: yes
  tasks:
    - name: install_pexpect
      yum: name=pexpect state=installed
    - name: init_db
      init_graphite: user={{ user }} password={{ password }} email={{ email }} locale={{ locale }}
