- hosts: cdh5_journalnode
  gather_facts: no
  tasks:
    - name: start_journalnode
      service: name=hadoop-hdfs-journalnode state=started

- hosts: cdh5_namenode_primary
  gather_facts: no
  sudo: True
  sudo_user: hdfs
  tasks:
    - name: format_hdfs
      shell: yes | hdfs namenode -format

- hosts: cdh5_namenode_primary
  gather_facts: no
  tasks:
    - name: start_namenode_primary
      service: name=hadoop-hdfs-namenode state=started

- hosts: cdh5_namenode_backup
  gather_facts: no
  sudo: True
  sudo_user: hdfs
  tasks:
    - name: namenode_bootstrap
      shell: >
             yes Y | hdfs namenode -bootstrapStandby

- hosts: cdh5_namenode_backup
  gather_facts: no
  tasks:
    - name: start_namenode_backup
      service: name=hadoop-hdfs-namenode state=started
