- hosts: hadoop_journalnode
  gather_facts: no
  tasks:
    - name: start_daemons
      service: name={{ item }} state=started
      with_items:
        - hadoop-hdfs-journalnode

- hosts: hadoop_namenode
  gather_facts: no
  tasks:
    - name: start_daemons
      service: name={{ item }} state=started
      with_items:
        - hadoop-hdfs-namenode
        - hadoop-hdfs-zkfc

- hosts: hadoop_slave
  gather_facts: no
  tasks:
    - name: start_daemons
      service: name={{ item }} state=started
      with_items:
        - hadoop-hdfs-datanode
