- name: copy_spark-defaults.conf
  template: src=spark-defaults.conf.j2 dest=/etc/spark/conf/spark-defaults.conf

- name: copy_spark-env.sh
  template: src=spark-env.sh.j2 dest=/etc/spark/conf/spark-env.sh

- name: copy_metrics.properties
  template: src=metrics.properties.j2 dest=/etc/spark/conf/metrics.properties

- name: copy_profile_of_spark
  template: src=spark.sh.j2 dest=/etc/profile.d/spark.sh
