- hosts: '{{server | default("hadoop_client") }}'
  vars:
    spark_comm_src_dir: '/usr/src/spark'
    spark_comm_version: 'master'
  tasks:
    - name: make_spark_src_directory
      file: path={{ spark_comm_src_dir }} state=directory
    
    - name: git_clone_spark_sources
      git: repo=https://github.com/apache/spark.git dest={{ spark_comm_src_dir }}/{{ spark_comm_version }} version={{ spark_comm_version }}

    - name: alternatives_spark_sources
      alternatives: name=spark_src path={{ spark_comm_src_dir }}/{{ spark_comm_version }} link={{ spark_comm_src_dir }}/default
    
    - name: build_spark
      shell: yes y | MAVEN_OPTS="-Xmx2g -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=512m" bash make-distribution.sh --tgz -Pnetlib-lgpl -Pyarn -Phadoop-2.4 -Dhadoop.version=2.4.0 -Phive -Phive-thriftserve -e chdir={{ spark_comm_src_dir }}/default
