- hosts: hadoop_pseudo
  gather_facts: no
  tasks:
    - name: start_namenode
      service: name=hadoop-hdfs-namenode state=started

    - name: wait_for_namenode_service_port
      wait_for: port=8020

    - name: start_secondarynamenode
      service: name=hadoop-hdfs-secondarynamenode state=started

    - name: wait_for_secondarynamenode_web_service_port_started
      wait_for: port=50090 state=started

    - name: start_datnode
      service: name=hadoop-hdfs-datanode state=started

    - name: wait_for_datanode_service_port
      wait_for: port=50020
