- hosts: hadoop_pseudo
  gather_facts: no
  tasks:
    - name: stop_daemons
      service: name=hadoop-yarn-resourcemanager state=stopped

    - name: wait_for_resourcemanager_web_service_port_stopped
      wait_for: port=8088 state=stopped

    - name: stop_daemons
      service: name=hadoop-yarn-nodemanager state=stopped

    - name: wait_for_nodemanager_service_port_stopped
      wait_for: port=8040 state=stopped

    - name: stop_daemons
      service: name=hadoop-mapreduce-historyserver state=stopped

    - name: wait_for_other_service_port_stopped
      wait_for: port=10020 state=stopped
