- name: copy_server.properties
  template: src=server.properties.j2 dest=/etc/confluent/kafka/server.properties

- name: copy_schema-registry.properties
  template: src=schema-registry.properties.j2 dest=/etc/confluent/schema-registry/schema-registry.properties

- name: copy_kafka-rest.properties
  template: src=kafka-rest.properties.j2 dest=/etc/confluent/kafka-rest/kafka-rest.properties

- include: supervisor_centos6.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- include: supervisor_centos7.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
