- name: copy_server.properties
  template: src=server.properties.j2 dest=/etc/kafka/server.properties

- name: mkdir_/var/lib/kafka
  file: path=/var/lib/kafka owner=kafka group=kafka state=directory

- name: chown_/var/log/kafka
  file: path=/var/log/kafka owner=kafka group=kafka state=directory

- name: copy_supervisor_configs
  template: src=kafka-server.ini.j2 dest=/etc/supervisord.d/kafka-server.ini
  notify: restart_supervisord
