- hosts: "{{ server | default('confluent_kafka_rest') }}"
  sudo: yes
  tasks:
    - name: start_kafka_rest
      shell: timeout 10 supervisorctl start kafka-rest
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
      failed_when: rc != 0 and rc != 124

    - name: start_kafka_rest
      shell: supervisorctl start kafka-rest
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'


