- hosts: "{{ server | default('confluent_schema_registry') }}"
  sudo: yes
  tasks:
    - name: start_schema_registry
      shell: timeout 10 supervisorctl start schema-registry
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

    - name: start_schema_registry
      shell: supervisorctl start schema-registry
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
