- hosts: "{{ server | default('confluent_kafka_cluster') }}"
  sudo: yes
  sudo_user: kafka
  tasks:
    - name: start_kafka_server
      shell: /usr/local/confluent_kafka/default/bin/kafka-server-start /etc/kafka/server.properties
