- hosts: "{{ server | default('confluent_kafka_rest') }}"
  sudo: yes
  tasks:
    - name: stop_kafka_rest
      shell: timeout 10 supervisorctl stop kafka-rest
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

    - name: stop_kafka_rest
      shell: supervisorctl stop kafka-rest
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
