- name: copy_supervisord.conf
  template: src=supervisord.conf.centos6.j2 dest=/etc/supervisord.conf
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- name: copy_supervisord.conf
  template: src=supervisord.conf.centos7.j2 dest=/etc/supervisord.conf
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
