- name: copy_hosts
  copy: src={{ common_hosts_tmpl }} dest=/etc/hosts
  when: common_hosts_replace

- name: set_hostname_to_inventory_hostname
  hostname: name={{ inventory_hostname }}
  when: common_config_hostname

- name: copy_sudoers
  template: src=sudoers.j2 dest=/etc/sudoers

- name: no_requiretty_for_root_and_wheel
  template: src={{ item }} dest=/etc/sudoers.d/{{ item }}
  with_items:
    - root
    - wheel
