- name: mkdir_zeppelin_dir
  file: path={{ zeppelin_dir }} owner=zeppelin group=zeppelin state=directory

- name: get_zeppelin_package
  get_url: url={{ zeppelin_package_base_url }}/{{ zeppelin_package_name }}{{ zeppelin_package_suffix }} dest={{ zeppelin_dir }}/{{ zeppelin_package_name }}{{ zeppelin_package_suffix }}
  sudo: yes
  sudo_user: zeppelin

- name: unarchive_zeppelin_package
  shell: tar xvzf {{ zeppelin_package_name }}{{ zeppelin_package_suffix }} chdir={{ zeppelin_dir }} creates={{ zeppelin_dir }}/{{ zeppelin_package_name }}/LICENSE
  sudo: yes
  sudo_user: zeppelin

- name: create_alternatives_link
  alternatives: name=zeppelin_package path={{ zeppelin_dir }}/{{ zeppelin_package_name }} link={{ zeppelin_dir }}/default
